name: Lagrange.Core NuGet Push

on:
  push:
    branches:
      - master
    paths:
      - "Lagrange.Core/**"
      - "Lagrange.Core.sln"
      - "LICENSE"
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Pack
        run: |
            dotnet build -c Release Lagrange.Core
            dotnet pack -c Release Lagrange.Core
            dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg Lagrange.Core

      - name: Push generated package to NuGet
        run: dotnet nuget push ./Lagrange.Core/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_KEY }}
